[[redirects]]
  from = "/api/*"
  to = "https://football-worker.mahdijadir38.workers.dev"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60"
